services:
  proxy:
    image: nginx
    volumes:
      # - "$PWD/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      # - "8081:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - DEBUG="true"
      - TZ=Asia/Shanghai
      - HTTPS_PROXY=http://oracle:8081
      - HTTP_PROXY=http://oracle:8081
      - NO_PROXY="localhost,127.0.0.1"
